//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogImages
    {
        public long Id { get; set; }
        public string FileName { get; set; }
        public string Alt { get; set; }
        public string Title { get; set; }
        public long BlogId { get; set; }
    
        public virtual Blogs Blogs { get; set; }
    }
}
