//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAttribute
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public bool IsRequired { get; set; }
        public ServiceWebsite.Core.TypeCodes.AttributeControlType AttributeControlTypeId { get; set; }
        public int DisplayOrder { get; set; }
        public string ResourceValue { get; set; }
        public string DefaultValue { get; set; }
    }
}
