//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPosPayment
    {
        public long Id { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string CreditCardMaskedNumber { get; set; }
        public short ExpireYear { get; set; }
        public byte ExpireMonth { get; set; }
        public string ClientIp { get; set; }
        public decimal PaymentAmount { get; set; }
        public ServiceWebsite.Core.TypeCodes.PostPaymentResultEnum PaymentResult { get; set; }
        public string ResultMessage { get; set; }
        public string TransactionId { get; set; }
        public Nullable<long> WebsitesId { get; set; }
    
        public virtual Websites Websites { get; set; }
    }
}
