//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchKeyword
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public ServiceWebsite.Core.TypeCodes.SearchKeywordType KeywordType { get; set; }
        public long KeywordId { get; set; }
    
        public virtual Keyword Keyword { get; set; }
    }
}
