//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceCategories()
        {
            this.ServiceCategories1 = new HashSet<ServiceCategories>();
            this.Services = new HashSet<Services>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Link { get; set; }
        public bool Active { get; set; }
        public int SortOrder { get; set; }
        public long LanguageId { get; set; }
        public bool ShowOnHomePage { get; set; }
        public string FileName { get; set; }
    
        public virtual Languages Languages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCategories> ServiceCategories1 { get; set; }
        public virtual ServiceCategories ServiceCategories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
