//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteFiles
    {
        public long Id { get; set; }
        public string FileName { get; set; }
        public Nullable<long> KeywordId { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<long> WebsiteId { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual Websites Websites { get; set; }
    }
}
